id: P9D034ADB
initial_creation_type: input
source_metadata:
  Title: Six Buddhist Nyaya tracts in Sanskrit
  Editor: Shastri, Haraprasad
  Publisher: The Asiatic Society
  Place of Publication: Calcutta
  Year: '1989'
  Apohasiddhiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:47:59.818171'
last_modified_at: '2022-03-08T16:47:59.818180'
